name: Water Fire Extinguisher

on:
  schedule:
    # Ejecutar todos los días a las 3:00 AM
    - cron: '50-59 0-23/2 * * *'

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl -X POST "https://extinguisherprices.com/api/save?q=Water%20Fire%20Extinguisher" -H "Accept: application/json"
