name: Halon Fire Extinguisher

on:
  schedule:
    # Ejecutar todos los días a las 3:00 AM
    - cron: '10-19 1-23/2 * * *'

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Call API
        run: |
          curl -X POST "https://extinguisherprices.com/api/save?q=Class%20D%20Fire%20Extinguisher" -H "Accept: application/json"
