# name: Call Amazon API and save data

# on:
#   schedule:
#     # Ejecutar todos los días a las 3:00 AM
#     - cron: '* * * * *'

# jobs:
#   call-api:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Call API
#         run: |
#           curl -X POST "https://extinguisherprices.com/api/save" -H "Accept: application/json"
