name: Scheduled Run Injest Script

on:
  schedule:
    # Runs the workflow at the beginning of every hour
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-injest:
    runs-on: ubuntu-latest

    env:  # Define environment variables here
      NODE_ENV: production
      DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
      AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
      AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
      AMAZON_ASSOCIATE_TAG: ${{ secrets.AMAZON_ASSOCIATE_TAG }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'  # Specify the version of Node.js you want to use

    - name: Install dependencies
      run: npm install

    - name: Run injest script
      run: node injest.js
